package com.consentiq.enums;

public enum PredefinedRuleScenario {
    NEW_CUSTOMER_DETECTED,
    CONSENT_NEARING_EXPIRY,
    EXPIRED_CONSENT,
    FIRST_SEND_NO_RESPONSE,
    REMINDER_1_NO_RESPONSE,
    REMINDER_2_NO_RESPONSE,
    DECLINED_RE_ENGAGEMENT_AFTER_COOLDOWN,
    VIP_PRIORITY_FAST_TRACK
}
